#TENSORS IN PYTHON

It's like set of blocks where each block form array then two array for matrices and so on

In [ ]:
import torch

In [ ]:
if torch.cuda.is_available():
  print("Using GPU")
  print(f"GPU available : {torch.cuda.get_device_name(0)}")
else :
  print("GPU not available.. Using CPU")

GPU not available.. Using CPU


In [ ]:
tensored=torch.tensor([[[0,255,255],
              [0,167,255],
              [0,123,123]],
             [[0,255,168],
              [0,123,255],
              [0,255,124]]])
print(f"number of element in tensor : {tensored.numel()}")
print(f"shape of tensor : {tensored.shape}")
print(f"dimension of tensor : {tensored.dim()}")

number of element in tensor : 18
shape of tensor : torch.Size([2, 3, 3])
dimension of tensor : 3


In [ ]:
print(tensored.reshape(6,-1).shape)
tensored.reshape(-1,6)

torch.Size([6, 3])


tensor([[  0, 255, 255,   0, 167, 255],
        [  0, 123, 123,   0, 255, 168],
        [  0, 123, 255,   0, 255, 124]])

In [ ]:
# arange(start,end,step,dtype,device)
torch.arange(5,10,2)

tensor([5, 7, 9])

## Creating Tensor

In [ ]:
#Initialising empty tensor these values are just numbers stored in that placed which this function allocate
torch.empty(2,3)

tensor([[1.5695e-43, 1.4153e-43, 5.6052e-44],
        [6.8664e-44, 7.8473e-44, 6.1657e-44]])

In [ ]:
# Initialising with zeros and ones
print(torch.zeros(2,3))
print("\n")
print(torch.ones(2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])


tensor([[1., 1., 1.],
        [1., 1., 1.]])


`tensor.device `: The device on which the tensor is stored (e.g., "cpu" or "cuda:0").


`tensor.requires_grad`: Whether PyTorch is tracking operations on the tensor for automatic differentiation.


In [ ]:
#initialising with random number from gaussian distribution
torch.rand(2,3)

tensor([[0.1322, 0.4760, 0.3989],
        [0.7317, 0.0720, 0.2252]])

In [ ]:
#we can also manually create tensor
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]]).dim()

2

In [ ]:
X = torch.arange(0,12).reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
#using linspace we give range and number of equally spaced elements we want in it
print(torch.linspace(0,10,20))
#using `eye` we create identity matrix
print("\n")
print(torch.eye(5))
#using full we can create tensor filled with certain elemnt
print("\n")
print(torch.full((2,3),5))

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])


tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


tensor([[5, 5, 5],
        [5, 5, 5]])


## TENSOR SLICING

includes the first `index (start)` but not the last `(stop)` .

In [ ]:
X[1:3]

tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
X[1:3,0:2]

tensor([[4, 5],
        [8, 9]])

#SEED
We can also set manual seed

In [ ]:
torch.rand(2,3)

tensor([[0.4022, 0.4708, 0.7814],
        [0.4900, 0.3698, 0.1926]])

In [ ]:
torch.rand(2,3)

tensor([[0.3151, 0.0408, 0.5553],
        [0.9050, 0.6724, 0.8179]])

In [ ]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
torch.rand(2,3)

tensor([[0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]])

# Copying existing tensor

In [ ]:
Y=torch.empty_like(X)
Y

tensor([[8030883940602478592, 7307199746910528123, 2475047244994847347,
         8318840530341473373],
        [4189021028717916783, 8458642046707773984, 7022364572756439922,
         3184663000500040818],
        [7017841271895826976, 7143407337307529588, 8104636957451185263,
         8243118355370701669]])

In [ ]:
torch.ones_like(X)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

# Arithematic operations on tensor


In [ ]:
A = torch.arange(0,12).reshape(2,-1)
B = torch.arange(12,24).reshape(2,-1)
print(A)
print("\n")
print(B)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])


tensor([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])


In [ ]:
A+B

tensor([[12, 14, 16, 18, 20, 22],
        [24, 26, 28, 30, 32, 34]])

In [ ]:
A-B

tensor([[-12, -12, -12, -12, -12, -12],
        [-12, -12, -12, -12, -12, -12]])

In [ ]:
A*B

tensor([[  0,  13,  28,  45,  64,  85],
        [108, 133, 160, 189, 220, 253]])

In [ ]:
A/B

tensor([[0.0000, 0.0769, 0.1429, 0.2000, 0.2500, 0.2941],
        [0.3333, 0.3684, 0.4000, 0.4286, 0.4545, 0.4783]])

In [ ]:
torch.cat((A,B),dim=0)
torch.cat((A,B),dim=1)

tensor([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17],
        [ 6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22, 23]])

In [ ]:
A==B

tensor([[False, False, False, False, False, False],
        [False, False, False, False, False, False]])

In [ ]:
A>B

tensor([[False, False, False, False, False, False],
        [False, False, False, False, False, False]])

In [ ]:
A<B

tensor([[True, True, True, True, True, True],
        [True, True, True, True, True, True]])

In [ ]:
A.sum()

tensor(66)

In [ ]:
print(A.sum(dim=0))
print(A.sum(dim=1))

tensor([ 6,  8, 10, 12, 14, 16])
tensor([15, 51])


#Broadcasting

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
a+b,b+a

(tensor([[0, 1],
         [1, 2],
         [2, 3]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [ ]:
a-b

tensor([[ 0, -1],
        [ 1,  0],
        [ 2,  1]])

In [ ]:
a*b

tensor([[0, 0],
        [0, 1],
        [0, 2]])

In [ ]:
a/b

tensor([[nan, 0.],
        [inf, 1.],
        [inf, 2.]])

#Memory saving in torch

Running operations can cause new memory to be allocated to host results. For example, if we write Y = X + Y, we dereference the tensor that Y used to point to and instead point Y at the newly allocated memory. We can demonstrate this issue with Python’s id() function, which gives us the exact address of the referenced object in memory. Note that after we run Y = Y + X, id(Y) points to a different location. That is because Python first evaluates Y + X, allocating new memory for the result and then points Y to this new location in memory.

In [ ]:
A,B

(tensor([[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]]),
 tensor([[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]))

In [ ]:
id(A)

131953583438160

In [ ]:
A=A+B
id(A)

131952332355248

In [ ]:
A

tensor([[12, 14, 16, 18, 20, 22],
        [24, 26, 28, 30, 32, 34]])

This might be undesirable for two reasons. First, we do not want to run around allocating memory unnecessarily all the time. In machine learning, we often have hundreds of megabytes of parameters and update all of them multiple times per second. Whenever possible, we want to perform these updates in place. Second, we might point at the same parameters from multiple variables. If we do not update in place, we must be careful to update all of these references, lest we spring a memory leak or inadvertently refer to stale parameters.

In [ ]:
#we can use [:]
Z=torch.ones_like(A)
print(Z)
print(id(Z))
Z[:]=A+B
print(id(Z))

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]])
131952333941616
131952333941616


In [ ]:
#we can also use X[:] = X + Y or X += Y to reduce the memory overhead of the operation.
print(id(A))
A+=B
print(id(A))


131952332355248
131952332355248


#changing types

In [ ]:
X = A.numpy()
Y = torch.from_numpy(X)
type(X), type(Y)

(numpy.ndarray, torch.Tensor)

In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [ ]:

type(a), type(a.item()), type(float(a)), type(int(a))

(torch.Tensor, float, float, int)